service: backoffice

provider:
  name: aws
  memorySize: 128
  timeout: 30
  runtime: nodejs10.x
  profile: ${env:PROFILE}
  stage: ${env:STAGE}
  region: ${env:REGION}
  versionFunctions: false
  iamRoleStatements:
    - Effect: "Allow"
      Action:
        - "cognito-idp:*"
        - "logs:CreateLogGroup"
        - "logs:CreateLogStream"
        - "logs:PutLogEvents"
        - "ec2:CreateNetworkInterface"
        - "ec2:DescribeNetworkInterfaces"
        - "ec2:DeleteNetworkInterface"
        - "dynamodb:*"
      Resource: "*"

plugins:
  - serverless-offline
  - serverless-dotenv-plugin
  # - serverless-mocha-plugin
  # - serverless-api-gateway-caching
  - serverless-pseudo-parameters  

# custom:
#   apiGatewayCaching: # Enable or disable caching globally
#     enabled: true
#     # clusterSize: '1.6' # defaults to '0.5'
#     # ttlInSeconds: 60 # defaults to the maximum allowed: 3600
#     # dataEncrypted: false # defaults to false
#     perKeyInvalidation:
#       requireAuthorization: false # default is true
#       # handleUnauthorizedRequests: Ignore # default is "IgnoreWithWarning"

functions:
  Proxy:
    handler: proxy.proxy
    events:
      - http:
          path: /{proxy+}
          method: get
          cors: true